// Canal bidireccional agente <-> control plane sobre gRPC (HTTP/2).
//
// Sustituye al latido HTTP como transporte preferido: el agente abre UN stream
// saliente de larga vida (mismo puerto :8080, misma mTLS) y por él viajan, en
// ambos sentidos y al instante:
//   agente -> control plane: hello (registro), snapshots, resultados de acciones
//   control plane -> agente: ack (intervalo) y ACCIONES según la GUI las encola
//
// La ventaja sobre HTTP es la vuelta: antes las órdenes esperaban al siguiente
// latido (hasta N segundos); con el stream llegan en cuanto se encolan.
//
// Los cuerpos grandes (Snapshot, Action, ActionResult) viajan como JSON de
// pkg/api A PROPÓSITO: pkg/api es la única fuente de verdad del esquema (misma
// validación, mismos tests) y así el transporte HTTP y el gRPC no pueden
// divergir. El proto solo define el SOBRE (quién habla y qué tipo de mensaje).
//
// Regenerar (make proto):
//   protoc --go_out=. --go_opt=module=github.com/atlasctl/atlas \
//          --go-grpc_out=. --go-grpc_opt=module=github.com/atlasctl/atlas \
//          proto/atlas/v1/channel.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: proto/atlas/v1/channel.proto

package channelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AgentChannel_Connect_FullMethodName = "/atlas.v1.AgentChannel/Connect"
)

// AgentChannelClient is the client API for AgentChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentChannel es el servicio que expone el control plane a los agentes.
type AgentChannelClient interface {
	// Connect es el stream bidireccional de larga vida. El PRIMER mensaje del
	// agente debe ser Hello; el control plane responde Ack y a partir de ahí
	// ambos lados hablan cuando quieren.
	Connect(ctx context.Context, opts ...grpc.CallOption) (AgentChannel_ConnectClient, error)
}

type agentChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentChannelClient(cc grpc.ClientConnInterface) AgentChannelClient {
	return &agentChannelClient{cc}
}

func (c *agentChannelClient) Connect(ctx context.Context, opts ...grpc.CallOption) (AgentChannel_ConnectClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentChannel_ServiceDesc.Streams[0], AgentChannel_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &agentChannelConnectClient{ClientStream: stream}
	return x, nil
}

type AgentChannel_ConnectClient interface {
	Send(*AgentMessage) error
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type agentChannelConnectClient struct {
	grpc.ClientStream
}

func (x *agentChannelConnectClient) Send(m *AgentMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentChannelConnectClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentChannelServer is the server API for AgentChannel service.
// All implementations must embed UnimplementedAgentChannelServer
// for forward compatibility
//
// AgentChannel es el servicio que expone el control plane a los agentes.
type AgentChannelServer interface {
	// Connect es el stream bidireccional de larga vida. El PRIMER mensaje del
	// agente debe ser Hello; el control plane responde Ack y a partir de ahí
	// ambos lados hablan cuando quieren.
	Connect(AgentChannel_ConnectServer) error
	mustEmbedUnimplementedAgentChannelServer()
}

// UnimplementedAgentChannelServer must be embedded to have forward compatible implementations.
type UnimplementedAgentChannelServer struct {
}

func (UnimplementedAgentChannelServer) Connect(AgentChannel_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentChannelServer) mustEmbedUnimplementedAgentChannelServer() {}

// UnsafeAgentChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentChannelServer will
// result in compilation errors.
type UnsafeAgentChannelServer interface {
	mustEmbedUnimplementedAgentChannelServer()
}

func RegisterAgentChannelServer(s grpc.ServiceRegistrar, srv AgentChannelServer) {
	s.RegisterService(&AgentChannel_ServiceDesc, srv)
}

func _AgentChannel_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentChannelServer).Connect(&agentChannelConnectServer{ServerStream: stream})
}

type AgentChannel_ConnectServer interface {
	Send(*ServerMessage) error
	Recv() (*AgentMessage, error)
	grpc.ServerStream
}

type agentChannelConnectServer struct {
	grpc.ServerStream
}

func (x *agentChannelConnectServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentChannelConnectServer) Recv() (*AgentMessage, error) {
	m := new(AgentMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentChannel_ServiceDesc is the grpc.ServiceDesc for AgentChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atlas.v1.AgentChannel",
	HandlerType: (*AgentChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentChannel_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/atlas/v1/channel.proto",
}
