// Canal bidireccional agente <-> control plane sobre gRPC (HTTP/2).
//
// Sustituye al latido HTTP como transporte preferido: el agente abre UN stream
// saliente de larga vida (mismo puerto :8080, misma mTLS) y por él viajan, en
// ambos sentidos y al instante:
//   agente -> control plane: hello (registro), snapshots, resultados de acciones
//   control plane -> agente: ack (intervalo) y ACCIONES según la GUI las encola
//
// La ventaja sobre HTTP es la vuelta: antes las órdenes esperaban al siguiente
// latido (hasta N segundos); con el stream llegan en cuanto se encolan.
//
// Los cuerpos grandes (Snapshot, Action, ActionResult) viajan como JSON de
// pkg/api A PROPÓSITO: pkg/api es la única fuente de verdad del esquema (misma
// validación, mismos tests) y así el transporte HTTP y el gRPC no pueden
// divergir. El proto solo define el SOBRE (quién habla y qué tipo de mensaje).
//
// Regenerar (make proto):
//   protoc --go_out=. --go_opt=module=github.com/atlasctl/atlas \
//          --go-grpc_out=. --go-grpc_opt=module=github.com/atlasctl/atlas \
//          proto/atlas/v1/channel.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: proto/atlas/v1/channel.proto

package channelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentMessage: lo que el agente puede enviar por el stream.
type AgentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_SnapshotJson
	//	*AgentMessage_ResultJson
	Msg isAgentMessage_Msg `protobuf_oneof:"msg"`
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_atlas_v1_channel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_v1_channel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_atlas_v1_channel_proto_rawDescGZIP(), []int{0}
}

func (m *AgentMessage) GetMsg() isAgentMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x, ok := x.GetMsg().(*AgentMessage_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *AgentMessage) GetSnapshotJson() []byte {
	if x, ok := x.GetMsg().(*AgentMessage_SnapshotJson); ok {
		return x.SnapshotJson
	}
	return nil
}

func (x *AgentMessage) GetResultJson() []byte {
	if x, ok := x.GetMsg().(*AgentMessage_ResultJson); ok {
		return x.ResultJson
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // primer mensaje: registro del clúster
}

type AgentMessage_SnapshotJson struct {
	SnapshotJson []byte `protobuf:"bytes,2,opt,name=snapshot_json,json=snapshotJson,proto3,oneof"` // api.Snapshot (JSON) — el "latido" periódico
}

type AgentMessage_ResultJson struct {
	ResultJson []byte `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3,oneof"` // api.ActionResult (JSON) — al terminar una acción
}

func (*AgentMessage_Hello) isAgentMessage_Msg() {}

func (*AgentMessage_SnapshotJson) isAgentMessage_Msg() {}

func (*AgentMessage_ResultJson) isAgentMessage_Msg() {}

// ServerMessage: lo que el control plane puede enviar por el stream.
type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ServerMessage_Ack
	//	*ServerMessage_ActionJson
	Msg isServerMessage_Msg `protobuf_oneof:"msg"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_atlas_v1_channel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_v1_channel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_atlas_v1_channel_proto_rawDescGZIP(), []int{1}
}

func (m *ServerMessage) GetMsg() isServerMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ServerMessage) GetAck() *Ack {
	if x, ok := x.GetMsg().(*ServerMessage_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *ServerMessage) GetActionJson() []byte {
	if x, ok := x.GetMsg().(*ServerMessage_ActionJson); ok {
		return x.ActionJson
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,1,opt,name=ack,proto3,oneof"` // respuesta al Hello
}

type ServerMessage_ActionJson struct {
	ActionJson []byte `protobuf:"bytes,2,opt,name=action_json,json=actionJson,proto3,oneof"` // api.Action (JSON) — orden de la GUI, al instante
}

func (*ServerMessage_Ack) isServerMessage_Msg() {}

func (*ServerMessage_ActionJson) isServerMessage_Msg() {}

// Hello registra el clúster (mismos campos que api.RegisterRequest).
type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterId    string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider     string `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	AgentVersion string `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_atlas_v1_channel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_v1_channel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_atlas_v1_channel_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hello) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// Ack confirma el registro. No devuelve token: el propio stream (autenticado
// por mTLS) ES la sesión; el control plane lo guarda internamente.
type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SnapshotIntervalSeconds int32 `protobuf:"varint,1,opt,name=snapshot_interval_seconds,json=snapshotIntervalSeconds,proto3" json:"snapshot_interval_seconds,omitempty"` // cadencia de snapshots que se pide
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_atlas_v1_channel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_v1_channel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_atlas_v1_channel_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetSnapshotIntervalSeconds() int32 {
	if x != nil {
		return x.SnapshotIntervalSeconds
	}
	return 0
}

var File_proto_atlas_v1_channel_proto protoreflect.FileDescriptor

var file_proto_atlas_v1_channel_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x61, 0x74, 0x6c, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x74, 0x6c, 0x61, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x12, 0x25, 0x0a, 0x0d, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0b, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x42, 0x05, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x5c, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x6b,
	0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x21, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x73, 0x6f, 0x6e, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x7b, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x41,
	0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x3a, 0x0a, 0x19, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x32, 0x4e, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x3e, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x16, 0x2e, 0x61,
	0x74, 0x6c, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x74, 0x6c, 0x61, 0x73, 0x63, 0x74, 0x6c, 0x2f, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_atlas_v1_channel_proto_rawDescOnce sync.Once
	file_proto_atlas_v1_channel_proto_rawDescData = file_proto_atlas_v1_channel_proto_rawDesc
)

func file_proto_atlas_v1_channel_proto_rawDescGZIP() []byte {
	file_proto_atlas_v1_channel_proto_rawDescOnce.Do(func() {
		file_proto_atlas_v1_channel_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_atlas_v1_channel_proto_rawDescData)
	})
	return file_proto_atlas_v1_channel_proto_rawDescData
}

var file_proto_atlas_v1_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_atlas_v1_channel_proto_goTypes = []any{
	(*AgentMessage)(nil),  // 0: atlas.v1.AgentMessage
	(*ServerMessage)(nil), // 1: atlas.v1.ServerMessage
	(*Hello)(nil),         // 2: atlas.v1.Hello
	(*Ack)(nil),           // 3: atlas.v1.Ack
}
var file_proto_atlas_v1_channel_proto_depIdxs = []int32{
	2, // 0: atlas.v1.AgentMessage.hello:type_name -> atlas.v1.Hello
	3, // 1: atlas.v1.ServerMessage.ack:type_name -> atlas.v1.Ack
	0, // 2: atlas.v1.AgentChannel.Connect:input_type -> atlas.v1.AgentMessage
	1, // 3: atlas.v1.AgentChannel.Connect:output_type -> atlas.v1.ServerMessage
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_atlas_v1_channel_proto_init() }
func file_proto_atlas_v1_channel_proto_init() {
	if File_proto_atlas_v1_channel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_atlas_v1_channel_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AgentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_atlas_v1_channel_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_atlas_v1_channel_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_atlas_v1_channel_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_atlas_v1_channel_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_SnapshotJson)(nil),
		(*AgentMessage_ResultJson)(nil),
	}
	file_proto_atlas_v1_channel_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Ack)(nil),
		(*ServerMessage_ActionJson)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_atlas_v1_channel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_atlas_v1_channel_proto_goTypes,
		DependencyIndexes: file_proto_atlas_v1_channel_proto_depIdxs,
		MessageInfos:      file_proto_atlas_v1_channel_proto_msgTypes,
	}.Build()
	File_proto_atlas_v1_channel_proto = out.File
	file_proto_atlas_v1_channel_proto_rawDesc = nil
	file_proto_atlas_v1_channel_proto_goTypes = nil
	file_proto_atlas_v1_channel_proto_depIdxs = nil
}
